include:
  - project: 'ng/open-base'
    ref: main
    file: '/templates/gitlab.yml'

build:
  extends: .maven-build
  only:
    refs:
      - branches
  except:
    refs:
      - main

deploy:
  extends: .maven-deploy
  only:
    refs:
      - tags
      - main
